### ISSUE TITLE
Make the library to loosly match at both ends of the URL

### ISSUE THREAD

**Issue by laszbalo** [lukeed/regexparam#10]
I am using this library to convert Express routes to `RegExp`s and then give those `RegExp`s to Workbox.
My issue is that Workbox matches the generated `RegExp`s to absolute URLs. Therefore, I added an option to optionally make the matching *loose at the start* as well:

```javascript
export default function (str, looseStart, looseEnd) {
	if (str instanceof RegExp) return { keys:false, pattern:str };
	var c, o, tmp, ext, keys=[], pattern='', arr = str.split('/');
	arr[0] || arr.shift();

	while (tmp = arr.shift()) {
		c = tmp[0];
		if (c === '*') {
			keys.push('wild');
			pattern += '/(.*)';
		} else if (c === ':') {
			o = tmp.indexOf('?', 1);
			ext = tmp.indexOf('.', 1);
			keys.push( tmp.substring(1, !!~o ? o : !!~ext ? ext : tmp.length) );
			pattern += !!~o && !~ext ? '(?:/([^/]+?))?' : '/([^/]+?)';
			if (!!~ext) pattern += (!!~o ? '?' : '') + '\\' + tmp.substring(ext);
		} else {
			pattern += '/' + tmp;
		}
	}

	return {
		keys: keys,
		pattern: new RegExp((looseStart ? '' : '^') + pattern + (looseEnd ? '(?=$|\\?|\/)' : '\/?$'), 'i')
	};
}
```

So, 
```javascript
rgx('/users/:name', true).pattern.test('https://example.com/users/lukeed'); //=> true
rgx('/users/:name', true, true).pattern.test('https://example.com/users/lukeed/repos'); //=> true
```

Would you consider adding this feature to the library?

**Comment by lukeed** [comment]
Hey,

No, thank you. This seems like a wildly dangerous idea and could (easily) render your router effectively useless. It also means that the `base` parameter is meaningless, since route-patterns could now match _anywhere_ within the entire URL. No point of a base path with that behavior.

Appreciate it though :)

**Comment by laszbalo** [comment]
Thanks for taking the time to look into this. I understand that you don't want this into your library.

Personally had similar feelings about this proposal, but **for my defense**, this is how [Workbox actually works](https://developers.google.com/web/tools/workbox/modules/workbox-routing#how_to_register_a_regular_expression_route) for *same origin* requests.
 
From their docs:

```javascript
new RegExp('/styles/.*\\.css') // NOTE: The origin where Workbox is running is example.com
```

The above `RegExp` will match all of the following `URL`s:
* https://example.com/styles/main.css
* https://example.com/styles/nested/file.css
* https://example.com/nested/styles/directory.css


However, I did not think through the possible implications of this change could have on people who use your library differently. (in Node.js, etc)

**Comment by lukeed** [comment]
No worries!

Yes, but Workbox is primarily concerned with assets and directory relationships/structures, typically with extension information. As with your example, it says "any CSS files inside styles", which allows it to be anywhere so long as it's a CSS file directly within `styles`.

That said, this will also match:

```
example.com/foo/styles/main.css/oops
```

But that's fine for Workbox because that doesn't/won't happen 99.999999% of the time
