### ISSUE TITLE
Publishing on Deno

### ISSUE THREAD

**Issue by talentlessguy** [lukeed/regexparam#13]
Would be cool to have this library published on Deno. Although, it imports fine from `import rg from 'https://esm.sh/regexparam'` but having it on the Deno registry could bring more users to the library.

In case you're interested: https://dev.to/craigmorten/how-to-publish-deno-modules-2cg6

**Comment by lukeed** [comment]
It took a little bit of fiddling, but `regexparam` is now on the Deno registry 👍 

All these options work:

```ts
import regexparam from 'https://esm.sh/regexparam';
import regexparam from 'https://cdn.skypack.dev/regexparam';
import regexparam from 'https://deno.land/x/regexparam/src/index.js';
```

I'll look into the Deno pathing a bit more, so that the `/src/index.js` part isn't needed. I imagine the `exports` map will be followed, but I don't imagine it would build files? Eg, `exports.import: "./dist/index.mjs"` would probably fail since the `dist` dir is hidden from git.

**Comment by lukeed** [comment]
Follow up –

The `deno.land` URL will stay as it is. There's no resolver/mapping logic on the deno registry. At best, there's `?subdir` but then that means [the module's landing page](https://deno.land/x/regexparam@v1.3.0) wouldn't have a README attached. I think this is fine since Deno users are used to / expecting verbose URL addresses.

**Comment by talentlessguy** [comment]
omg thanks for publishing on Deno!

regarding the URL, it's true, there's no resolver logic (that's the point of Deno haha) so having a full URL is completely fine.

thanks again for publishing, I will use the deno version of regexparam in one of my projects

**Comment by lukeed** [comment]
Cool, not a problem :)

**Comment by talentlessguy** [comment]
one tiny issue (but not really that important). Deno cannot catch the .d.ts file so it infers automatic types from JS (so rg params have `any` type)

![image](https://user-images.githubusercontent.com/35937217/119275653-f592a000-bc1e-11eb-8e64-08a53e6079ee.png)

AFAIK this can be solved by moving both files into the same dir and have same filename, e.g. like this:

```
index.js
index.d.ts
```

Although, it's not required now. It works good enough for me :)

**Comment by lukeed** [comment]
Ok thanks, good to know. Will have that fixed for the next version that goes out 👍
